name: GitHub Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: echo " ========== start building ========== "

      - name: Test
        run: echo " ========== start testing ========== "

      - name: Deploy
        run: echo " ========== start deploying ========== "
